spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbssmtest?serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin  # 用户名
      password: 123456  # 密码