server:
  port: 90
  servlet:
    encoding:
      charset: utf-8

jasypt:
  encryptor:
    password: abc$%^


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbssmtest?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true







